### ISSUE TITLE
No projeto final não tem login !

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [cod3rcursos/meat-app-template#1]
Não ficou legal isso... um projeto template e outro projeto final sem o login que estar no template..
Vai ter que mudar as rodas vai da um trabalhão para por esse login no projeto final.
Esperamos uma versão final com tudo isso junto e com paginação com Combobox etc...
Fazendo isso vou comprar todos seus cursos, e ainda vou divulgar para os meus 34 colegas desenvolvedores Delphi Forms Clipper e Javeiros aqui no trabalho..

Att.

**Comment by tarsobessa** [comment]
Olá,

O projeto final contém a implementação feita no curso, incluindo o login. Deixei apenas em um branch separado chamado "autenticacao" porque contém refactorings importantes que poderiam atrapalhar as pessoas que ainda não tinham chegado naquele ponto.

Você pode checar os arquivos aqui: https://github.com/cod3rcursos/meat-app-final/tree/autenticacao

Abraços.
